firmness_of_opportunity:
  Green: "DAF / GIP or 'one pager' prepared and all internal approvals obtained from all impacted portfolios. Start date of IT effort known"
  Amber: "DAF / GIP or 'one pager' in progress. Impacted portfolio approvals expected within 2 months. Tentative start date of IT effort known"
  Red: "DAF / GIP or 'one pager' not yet prepared. Approvals not expected for >3 months. Start date of IT effort unknown"

